# Enhanced Bybit Trading System - Database Configuration
# All trading system configurations are now stored in the MySQL database.
# This file only contains database connection settings.

database:
  # Database type: mysql only
  type: "mysql"
  
  # MySQL settings
  host: "localhost"
  port: 3306
  database: "bybit_trading_system"
  username: "root"
  password: "your_secure_password"
  
  # Connection pool settings
  pool_size: 10
  max_overflow: 20
  pool_timeout: 30
  pool_recycle: 3600
  echo_sql: false

# Configuration Management
config:
  # Which configuration to load from database
  config_name: "default"
  
  # Auto-create default config if not found
  auto_create_default: true
  
  # Backup configuration to YAML on changes
  backup_on_update: true
  backup_directory: "config_backups"

# System Settings
system:
  # Enable database logging
  enable_db_logging: true
  
  # Automatic cleanup settings
  auto_cleanup_enabled: true
  cleanup_days_to_keep: 30
  cleanup_schedule: "daily"  # daily, weekly, monthly
  
  # Database maintenance
  auto_vacuum: true
  backup_on_startup: false

# Timeframe Configuration (hardcoded for consistency)
# Primary timeframe: 15m
# Confirmation timeframes: 1h, 4h
# These values are enforced in the database configuration